config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  scope module: :public do
    root to: "homes#top"
    resources :users, except: [:destroy,:new,:create] do
      resource :relationships, only: [:create, :destroy]
  	  get 'followings' => 'relationships#followings', as: 'followings'
  	  get 'followers' => 'relationships#followers', as: 'followers'
    end
    resource :relationships, only: [:create,:destroy]
    patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    resources :posts, except: [:edit,:update] do
       resource :post_goods, only: [:create, :destroy]
       resource :post_bads, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :genres, only: [:index,:create,:show] do
      resource :genre_likes, only: [:create, :destroy]
    end
    get '/search', to: 'searches#search'
    delete 'notifications/destroy_all', to: 'notifications#destroy_all', as: 'notifications_destroy_all'
    resources :notifications, only: [:index,:destroy]
  end

  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index,:update,:show]
    resources :posts, only: [:index,:destroy]
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }

  has_many :post_comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :genre_likes, dependent: :destroy
  has_many :genres, through: :genre_likes, dependent: :destroy
  has_many :post_goods, dependent: :destroy
  has_many :post_bads, dependent: :destroy

 # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  has_many :view_counts, dependent: :destroy

  scope :active, -> { where(is_deleted: false) }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-min.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content)
    User.active.where(['name LIKE ?', "%#{content}%"])
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ?",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def update
    if params[:sort_update]
      user = User.find(params[:id])
      user.update(is_deleted: true)
      user.post_comments.destroy_all
      user.followings.destroy_all
      user.followers.destroy_all
      user.active_notifications.destroy_all
      user.post_goods.destroy_all
      redirect_to request.referer
    else
      user = User.find(params[:id])
      user.update(is_deleted: false)
      redirect_to request.referer
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">

      <div class="row-md-10 pb-3">
        <h2>Users</h2>
      </div>

      <div class="row-md-10 pb-3">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th>
                ID
              </th>
              <th>
                Name
              </th>
              <th>
                Email
              </th>
              <th>
                Status
              </th>
              <th>
                Edit account
              </th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <th>
                <%= user.id %>
              </th>
              <th>
                <%= link_to user.name, admin_user_path(user) %>
              </th>
              <th>
                <%= user.email %>
              </th>
              <th>
                <% if user.is_deleted == false %>
                Active
                <% else %>
                Inactive
                <% end %>
              </th>
              <th>
                <% if user.is_deleted == false %>
                  <%= link_to "Delete account",admin_user_path(user,sort_update: "true"), method: :patch, class: "btn btn-outline-danger btn-sm" %>
                <% else %>
                  <%= link_to "Activate account",admin_user_path(user), method: :patch, class: "btn btn-outline-success btn-sm" %>
                <% end %>
              </th>
            </tr>
            <% end %>
          </tbody>
        </table>
      	<div>
          <p><%= paginate @users %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="media mt-2">
        <%= image_tag @user.get_profile_image(100,100), class: "rounded-circle" %>
        <div class="media-body ml-3">
          <h5 class="my-3"><%= @user.name %></h5>
          <%= @user.created_at %>
        </div>
      </div>
      <div class="my-3 border-top">
        <h5 class="my-2">About</h5>
        <p><%= @user.biography %></p>
      </div>
    </div>
  </div>

  <h5><%= @posts.count %>Stories</h5>
  <% @posts.each do |f| %>
    <div class="card my-3">
      <div class="row no-gutters">
        <div class="col-md-auto">
          <div class="card-body">
            <div class="row">
              <h6 class="card-title">Title:<%= f.title %></h6>
              <%= link_to f.user.name, admin_user_path(f.user.id), class: "ml-3 text-muted" %>
              <%= link_to "Delete", admin_post_path(f.id), method: :delete, class: "ml-3 text-danger", data: { confirm: "本当に削除しますか？" } %>
            </div>
            <a href="<%= f.content_url %>"><%= f.content_url %></a>
            <p class="card-text"><%= f.description %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>