config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  scope module: :public do
    root to: "homes#top"
    resources :users, except: [:destroy,:new,:create] do
      resource :relationships, only: [:create, :destroy]
  	  get 'followings' => 'relationships#followings', as: 'followings'
  	  get 'followers' => 'relationships#followers', as: 'followers'
    end
    resource :relationships, only: [:create,:destroy]
    patch '/users/:id/withdraw' => 'users#withdraw', as: 'withdraw'
    resources :posts, except: [:edit,:update] do
       resource :post_goods, only: [:create, :destroy]
       resource :post_bads, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :genres, only: [:index,:create,:show] do
      resource :genre_likes, only: [:create, :destroy]
    end
    get '/search', to: 'searches#search'
    delete 'notifications/destroy_all', to: 'notifications#destroy_all', as: 'notifications_destroy_all'
    resources :notifications, only: [:index,:destroy]
  end

  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index,:update,:show]
    resources :posts, only: [:index,:destroy]
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row mx-auto">
    <div id="error_explanation">
      <h3 class="text-danger"><%= obj.errors.count %> 件のエラーが発生しました</h3>
      <ul class="text-danger">
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white p-3">
  <h5 class="my-0 mr-md-auto font-weight-normal">
    <%= link_to "Article Aggregator", root_path, class: "blog-header-logo text-dark" %>
  </h5>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
  <% if user_signed_in? %>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ml-3">
      <li class="nav-item">
        <%= link_to notifications_path do %>
          <% if uncheck_notifications.any? %>
            <i class="far fa-bell fa-lg"></i>
            <i class="fas fa-circle fa-xs mb-2 pb-1"></i>
          <% else %>
            <i class="far fa-bell fa-lg"></i>
          <% end %>
        <% end %>
      </li>
    </ul>
    <div class="form-inline mt-2 mt-md-0 mr-3">
      <%= form_with url: search_path, method: :get, local: true do |f| %>
        <%= f.text_field :content, class: "form-control mr-sm-2" %>
        <%= f.select :model, options_for_select({"User" => "user", "Post" => "post" }),{},{class: 'custom-select my-1 mr-sm-2'} %>
        <%= f.submit "Search", class: "btn btn-outline-primary" %>
      <% end %>
    </div>
    <%= link_to user_path(current_user) , class: "p-2 text-dark" do %>
      <%= image_tag current_user.get_profile_image(50,50), class: "rounded-circle" %>
    <% end %>
  <% end %>
  <% if admin_signed_in? %>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ml-3">
      <li class="nav-item">
        <%= link_to "Sign out", destroy_admin_session_path, method: :delete, class: "p-2 text-dark" %>
      </li>
      <li class="nav-item">
        <%= link_to "Posts", admin_posts_path, class: "p-2 text-dark" %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", admin_users_path, class: "p-2 text-dark" %>
      </li>
    </ul>
  <% end %>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% if flash[:notice] %>
  <div class="w-auto bg-success">
    <div class="container">
      <div class="row">
        <div class="col-8 mx-auto mt-3">
          <p class="text-center text-white font-weight-bold" id="notice">
            <%= flash[:notice] %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="w-auto bg-danger">
    <div class="container">
      <div class="row">
        <div class="col-8 mx-auto mt-3">
          <p class="text-center text-white font-weight-bold" id="notice">
            <%= flash[:alert] %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
   <div class="col-md-3 col-xl-2 sidebar bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <nav class="bd-links collapse show">
        <ul class="nav flex-column">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-home mr-1"></i>Home
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Popular", posts_path(sort_good: "true"), class: "dropdown-item" %>
              <%= link_to "New", posts_path , class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to users_path, class: "nav-link active" do %>
              <i class="fas fa-users mr-1"></i>Users
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_post_path, class: "nav-link active" do %>
              <i class="fas fa-plus mr-1"></i>Post
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to genres_path, class: "nav-link active" do %>
              <i class="fas fa-tags mr-1"></i>Genres
            <% end %>
          </li>
          <% current_user.genres.each do |genre| %>
            <li class="nav-item nav-link active">
              <%= link_to genre_genre_likes_path(genre), method: :delete do %>
                <i class="fas fa-minus-circle"></i>
              <% end %>
              <%= link_to genre.name, genre_path(genre.id) %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link active" do %>
              <i class="fas fa-sign-out-alt mr-1"></i>Sign out
            <% end %>
          </li>
        </ul>
      </nav>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArticleIntegrationApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/notice' %>
    <%= yield %>
  </body>
</html>